name: E2E - Netlify
on: pull_request
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: pnpm run build
      - name: Hold for Netlify
        uses: magne4000/wait-for-netlify-action@v4
        id: waitForDeployment
        with:
          site_id: '2c57d824-b734-40b4-837c-c71202c98b18'
          max_timeout: 180
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Test e2e deployed
        run: pnpm test:e2e
        working-directory: examples/app-netlify
        env:
          BASE_URL: ${{ steps.waitForDeployment.outputs.url }}
          NODE_ENV: production
