name: E2E - Cloudflare
on: pull_request
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: pnpm run build
      - run: pnpm run build
        working-directory: examples/app-cloudflare
      - name: Get Cloudflare Preview URL
        uses: zentered/cloudflare-preview-url@v1
        id: cloudflare_preview_url
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          cloudflare_project_id: 'universal-deploy'
          wait_until_ready: true
      - name: Print deployment url
        run: |
          if [ -z "$BASE_URL" ]; then
            echo "Error: deployment-url is not defined or empty"
            exit 1
          fi
          echo "Deployment URL: $BASE_URL"
        env:
          BASE_URL: ${{ steps.cloudflare_preview_url.outputs.preview_url }}
      - name: Test e2e deployed
        run: pnpm test:e2e
        working-directory: examples/app-cloudflare
        env:
          BASE_URL: ${{ steps.cloudflare_preview_url.outputs.preview_url }}
          NODE_ENV: production
