name: E2E - Deno
on: pull_request
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: pnpm run build
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts
      - run: deno run build
        working-directory: examples/app-node
      - name: Test e2e
        run: pnpm run test:e2e
        working-directory: examples/app-node
        env:
          RUN_CMD: deno run -A dist/server/index.js
          BASE_URL: http://127.0.0.1:3000
          NODE_ENV: production
