name: E2E - Bun
on: pull_request
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: pnpm run build
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.3'
      - run: bun run build
        working-directory: examples/app-node
      - name: Test e2e
        run: pnpm run test:e2e
        working-directory: examples/app-node
        env:
          RUN_CMD: bun --bun dist/server/index.js
          NODE_ENV: production
