name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [20]
      fail-fast: false
    name: 'Test on node-${{ matrix.node_version }}, ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set Node.js version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: pnpm install
      - run: pnpm exec playwright install chromium
      - run: pnpm run build
      - run: pnpm run test
        env:
          LANG: en_US
          HMR: 1
      - run: pnpm run test:types

  lint:
    name: Biome check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set Node.js version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run format:check
